# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Zigna
title: Zigna - Your AI Trading Tutor, Monitor and Companion
# ---- Jekyll settings ----
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-seo-tag

# Multilingual settings
languages: ["en", "es", "pt"]
default_lang: "en"
exclude_from_localization:
  - "assets"
  - "vendor"
  - "favicon.ico"
  - "favicon.png"
  - "icon.png"
  - "icon_1024x1024.png"
  - "icon_144x144.png"
  - "icon_192x192.png"
  - "icon_256x256.png"
  - "icon_384x384.png"
  - "icon_512x512.png"
  - "icont_1024_1024.png"
  - "logo.png"
parallel_localization: true

author: Zigna
description: >- # this means to ignore newlines until "baseurl:"
  Master profitable trading with personalized AI guidance, risk-free simulators, and real-time market intelligence. Whether you're taking your first trade or refining your strategy, Zigna teaches you to trade smarterâ€”not harder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zigna.app" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ZignaApp
color_primary: "#2a31ab;"
color_secondary: "#2b60f6;"

# Build settings
markdown: kramdown
permalink: pretty

google_analytics: "G-6QNFRMNM4X"

# Exclude directories and files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - .github/
  - _site/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
