# Zigna site
name: Zigna
title: Stop Trading Alone. Start Trading Smarter.

# ---- Main settings ----
author: Zigna
description: >- # this means to ignore newlines until "baseurl:"
  Stop guessing. Start winning. From your first trade to your thousandth, Zigna provides the real-time intelligence you need to trade smarterâ€”never harder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zigna.app" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ZignaApp
color_primary: "#2a31ab;"
color_secondary: "#2b60f6;"
google_analytics: "G-PP5MDV5HSH"

# ---- Multi-Language Settings ----
languages: ["en", "es", "pt"]
default_lang: "en"
exclude_from_localization:
  - "assets"
  - "vendor"
  - "favicon.ico"
  - "favicon.png"
  - "icon.png"
  - "icon_1024x1024.png"
  - "icon_144x144.png"
  - "icon_192x192.png"
  - "icon_256x256.png"
  - "logo.png"
parallel_localization: true

# ---- Jekyll settings ----
markdown: kramdown
permalink: pretty

# Exclude directories and files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - .github/
  - _site/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
