# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Zigna
title: Zigna - Your AI Trading Tutor, Monitor and Companion
lang: en
default_lang: en
languages: ["en", "pt", "es"]
exclude_from_localizations: ["assets", "vendor", "slides"]

plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

author: Zigna
description: >- # this means to ignore newlines until "baseurl:"
  Zigna te proporciona la forma más fácil de enviar o recibir señales de compra o venta para el mercado de valores.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zigna.app" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ZignaApp
color_primary: "#2a31ab;"
color_secondary: "#2b60f6;"

# Build settings
markdown: kramdown
theme: minima

#permalink: /:categories/:year/:month/:day/:title:output_ext

google_analytics: "G-1EW53HKMKV"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
